Repository MithrilJS/mithril.js, pull requests merged in 2018-11, with the labels that each got.

#2285 Abandon Closure Compiler in favor of UglifyES
  bundler/cli.js
  bundler/minify.js
  mithril.min.js
  package-lock.json
  package.json
Labels: workflow

#2268 Add `m.prop`
  docs/api.md
  docs/change-log.md
  docs/nav-methods.md
  docs/prop.md
  index.js
  util/prop.js
  util/tests/index.html
  util/tests/test-prop.js
Labels: enhancement

#1830 Examples: Pure reactive clone of the animation example
  examples/animation-stream/flowers.jpg
  examples/animation-stream/mosaic-stream.html
Labels: documentation, enhancement

#2175 Merge #2075 into next
  docs/change-log.md
  package-lock.json
  render/render.js
  render/tests/manual/iframe.html
  render/tests/manual/index.html
Labels: bug

#2286 Fix #1771 and probably others
  docs/change-log.md
  render/render.js
  render/tests/test-event.js
  test-utils/domMock.js
  test-utils/tests/test-domMock.js
Labels: backport to v1, bug

#2194 output mithril, stream and ospec esm versions on build - fixes #2112
  .eslintignore
  esm.js
  index.js
  mithril.min.mjs
  mithril.mjs
  ospec/esm.js
  ospec/ospec.mjs
  ospec/package.json
  package.json
  stream/package.json
  stream/stream.mjs
Labels: enhancement

#2314 Fix #1908, document fields.
  docs/change-log.md
  docs/request.md
Labels: bug

#2290 Simplify bundler a little
  bundler/bundle.js
  bundler/cli.js
  bundler/minify.js
  bundler/tests/test-bundler.js
  package-lock.json
  package.json
Labels: workflow

#2297 Reverse hook order for all but `onbeforeupdate`
  docs/change-log.md
  render/render.js
  render/tests/test-component.js
  render/tests/test-onbeforeupdate.js
Labels: breaking change proposal, bug

#2296 Officially drop IE9-10 support, pull out our hacks
  README.md
  api/redraw.js
  api/tests/test-redraw.js
  docs/change-log.md
  docs/contributing.md
  docs/index.md
  docs/lint.js
  docs/redraw.md
  docs/route.md
  module/module.js
  ospec/tests/test-ospec.js
  render/render.js
  request/tests/test-request.js
  test-utils/domMock.js
  test-utils/tests/test-components.js
  test-utils/tests/test-domMock.js
  tests/test-api.js
Labels: bug, documentation

#2250 Fix docs bug, advise against reusing `vnode.attrs` itself
  docs/change-log.md
  docs/components.md
Labels: bug, documentation

#2271 Create an Issues Submission Page Enhancement
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: meta/feedback

#2288 Fix `m.request`/`m.jsonp` to not mutate arguments, simplify code
  docs/change-log.md
  request/request.js
  test-utils/xhrMock.js
Labels: bug
