Repository MithrilJS/mithril.js, pull requests merged in 2022-05, with the labels that each got.

#2769 Enable --minimize-semver-change for pr-release
  .github/workflows/merge.yml
  .github/workflows/pr.yml
Labels: Area: Workflow

#2764 allow trailing slash for routes - fixes #2763
  api/tests/test-router.js
  pathname/parse.js
  pathname/tests/test-parsePathname.js
Labels: Type: Bug, Type: Breaking Change, Type: Release Blocker

#2746 Kick promise polyfill
  README.md
  api/router.js
  api/tests/test-router.js
  docs/animation.md
  docs/nav-methods.md
  docs/promise.md
  docs/request.md
  index.js
  mithril.js
  mithril.min.js
  promise/.eslintrc.js
  promise/polyfill.js
  promise/promise.js
  promise/tests/test-promise.js
  promise/tests/test.html
  render/tests/test-onbeforeremove.js
  request.js
  request/request.js
  request/tests/test-jsonp.js
  request/tests/test-request.js
Labels: Type: Breaking Change, major
